name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every 24 hours
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe Badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "nidharshana0402"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
